import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { WebSocketProvider } from "@/Context/WebSocket";
import ErrorBoundary from "@/components/ErrorBoundary";
import CMDProvider from "@/Context/CMDLogs";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary fallback={<div className="text-center w-full h-screen grid place-items-center text-2xl">Oopsie! You caused the crash dude, not us. Try again 🚀</div>}>
          <CMDProvider>
            <WebSocketProvider>
              {children}
            </WebSocketProvider>
          </CMDProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
